language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - yarn lint
  - yarn workspace @qio/type-test run test
  - yarn tsc -b
  - yarn test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

deploy:
  provider: script
  script: "./scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master